const router = require('express').Router();
const c = require('../controllers/jobController');
router.post('/create', c.createJob);
router.get('/feed', c.getNearbyJobs);
router.get('/applications/search', c.searchWorkerApplicants);
router.get('/worker/:workerPhone/applications', c.getWorkerApplications);
router.get('/farmer/by-phone/:farmerPhone', c.getFarmerJobsByPhone);
router.get('/:jobId/applications', c.getJobApplications);
router.post('/:jobId/apply', c.applyForJob);
router.post('/:jobId/applications/:applicationId/decision', c.decideApplication);
router.post('/applications/:applicationId/complete', c.completeJob);
router.get('/farmer/:farmerId', c.getFarmerJobs);
router.post('/:jobId/accept', c.applyForJob);
module.exports = router;
